server:
  command: socat TCP-L:12345,fork,reuseaddr EXEC:'sqlite /opt/sqlite/db',pty
  build: .
  volumes:
  - /tmp/sqlitedbs/test:/opt/sqlite/db
proxy:
  command: socat TCP-L:12346,fork,reuseaddr TCP:sqliteserver:12345
  build: .
  links:
  - server:sqliteserver
  ports:
  - 12346:12346
